### ISSUE TITLE
[요청] develop branch 파일 삭제 요청

### ISSUE THREAD

**Issue by c-peace** [ProjectFRIDAY/Plan-Dial-Renewal#13]
## 요청 사항
develop branch의 lib/screens/test.dart 파일을 삭제해 주세요.

## 요청 이유
test 목적으로 만든 파일이며, 본 프로젝트와 무관한 UI가 담겨 있습니다.

## 기타 사항
나중에 삭제해도 아무 문제 없으니 어느정도 마무리 된 후 지워도 상관 없습니다.

**Comment by Mango-Juice** [comment]
https://github.com/ProjectFRIDAY/Plan-Dial-Renewal/commit/6cf4ee0da04c8c6ca13ec294600170b9c25570bb 에서 처리 완료되었습니다.
